---
kind: pipeline
name: lint

platform:
  os: linux
  arch: amd64

steps:
- name: flake8
  image: python:3.7
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - flake8 ./ansibledoctor
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

---
kind: pipeline
name: test

platform:
  os: linux
  arch: amd64

steps:
- name: python35-pytest
  image: python:3.5
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - ansible-doctor --help
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python36-pytest
  image: python:3.6
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - ansible-doctor --help
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python37-pytest
  image: python:3.7
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - ansible-doctor --help
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

- name: python38-rc-pytest
  image: python:3.8-rc
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - ansible-doctor --help
  environment:
    PY_COLORS: 1
  depends_on:
  - clone

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- lint

---
kind: pipeline
name: security

platform:
  os: linux
  arch: amd64

steps:
- name: bandit
  image: python:3.7
  commands:
  - pip install -r test-requirements.txt -qq
  - pip install -qq .
  - bandit -r ./ansibledoctor -x ./ansibledoctor/tests
  environment:
    PY_COLORS: 1

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- test

---
kind: pipeline
name: build-package

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.7
  commands:
  - python setup.py sdist bdist_wheel

- name: checksum
  image: alpine
  commands:
  - cd dist/ && sha256sum * > ../sha256sum.txt

- name: publish-github
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_token
    files:
    - dist/*
    - sha256sum.txt
    note: CHANGELOG.md
    overwrite: true
    title: ${DRONE_TAG}
  when:
    ref:
    - refs/tags/**

- name: publish-pypi
  image: plugins/pypi
  settings:
    password:
      from_secret: pypi_password
    repository: https://upload.pypi.org/legacy/
    skip_build: true
    username:
      from_secret: pypi_username
  when:
    ref:
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: build-container-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: python:3.7
  commands:
  - python setup.py bdist_wheel

- name: dryrun
  image: plugins/docker:18-linux-amd64
  settings:
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: publish
  image: plugins/docker:18-linux-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: amd64
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: build-container-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: python:3.7
  commands:
  - python setup.py bdist_wheel

- name: dryrun
  image: plugins/docker:18-linux-arm64
  settings:
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: publish
  image: plugins/docker:18-linux-arm64
  settings:
    auto_tag: true
    auto_tag_suffix: arm64
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: build-container-arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: python:3.7
  commands:
  - python setup.py bdist_wheel

- name: dryrun
  image: plugins/docker:18-linux-arm
  settings:
    dockerfile: Dockerfile
    dry_run: true
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/pull/**

- name: publish
  image: plugins/docker:18-linux-arm
  settings:
    auto_tag: true
    auto_tag_suffix: arm
    dockerfile: Dockerfile
    password:
      from_secret: docker_password
    repo: xoxys/ansible-doctor
    username:
      from_secret: docker_username
  when:
    ref:
    - refs/heads/master
    - refs/tags/**

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  - refs/pull/**

depends_on:
- security

---
kind: pipeline
name: docs

platform:
  os: linux
  arch: amd64

concurrency:
  limit: 1

steps:
- name: assets
  image: byrnedo/alpine-curl
  commands:
  - mkdir -p docs/themes/hugo-geekdoc/
  - curl -L https://github.com/xoxys/hugo-geekdoc/releases/latest/download/hugo-geekdoc.tar.gz | tar -xz -C docs/themes/hugo-geekdoc/ --strip-components=1

- name: test
  image: klakegg/hugo:0.59.1-ext-alpine
  commands:
  - cd docs/ && hugo-official

- name: freeze
  image: appleboy/drone-ssh:1.5.5
  settings:
    host:
      from_secret: ssh_host
    key:
      from_secret: ssh_key
    script:
    - cp -R /var/www/virtual/geeklab/html/ansible-doctor.geekdocs.de/ /var/www/virtual/geeklab/html/ansibledoctor_freeze/
    - ln -sfn /var/www/virtual/geeklab/html/ansibledoctor_freeze /var/www/virtual/geeklab/ansible-doctor.geekdocs.de
    username:
      from_secret: ssh_username

- name: publish
  image: appleboy/drone-scp
  settings:
    host:
      from_secret: ssh_host
    key:
      from_secret: ssh_key
    rm: true
    source: docs/public/*
    strip_components: 2
    target: /var/www/virtual/geeklab/html/ansible-doctor.geekdocs.de/
    username:
      from_secret: ssh_username

- name: cleanup
  image: appleboy/drone-ssh:1.5.5
  settings:
    host:
      from_secret: ssh_host
    key:
      from_secret: ssh_key
    script:
    - ln -sfn /var/www/virtual/geeklab/html/ansible-doctor.geekdocs.de /var/www/virtual/geeklab/ansible-doctor.geekdocs.de
    - rm -rf /var/www/virtual/geeklab/html/ansibledoctor_freeze/
    username:
      from_secret: ssh_username

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**

depends_on:
- build-package
- build-container-amd64
- build-container-arm64
- build-container-arm

---
kind: pipeline
name: notifications

platform:
  os: linux
  arch: amd64

steps:
- name: manifest
  image: plugins/manifest
  settings:
    auto_tag: true
    ignore_missing: true
    password:
      from_secret: docker_password
    spec: manifest.tmpl
    username:
      from_secret: docker_username

- name: readme
  image: sheogorath/readme-to-dockerhub
  environment:
    DOCKERHUB_PASSWORD:
      from_secret: docker_password
    DOCKERHUB_REPO_NAME: ansible-doctor
    DOCKERHUB_REPO_PREFIX: xoxys
    DOCKERHUB_USERNAME:
      from_secret: docker_username
    README_PATH: README.md
    SHORT_DESCRIPTION: ansible-doctor - Simple annotation based documentation for your roles

- name: matrix
  image: plugins/matrix
  settings:
    homeserver:
      from_secret: matrix_homeserver
    password:
      from_secret: matrix_password
    roomid:
      from_secret: matrix_roomid
    template: "Status: **{{ build.status }}**<br/> Build: [{{ repo.Owner }}/{{ repo.Name }}]({{ build.link }}) ({{ build.branch }}) by {{ build.author }}<br/> Message: {{ build.message }}"
    username:
      from_secret: matrix_username

trigger:
  ref:
  - refs/heads/master
  - refs/tags/**
  status:
  - success
  - failure

depends_on:
- docs

---
kind: signature
hmac: 3b58fe1bfbb9628ccf96b9ffa8555eb46b1c54a763856c7c5c51ab989c22b196

...
