---
- id: ansible-doctor
  name: ansible-doctor
  description: Create annotation based documentation for your Ansible roles.
  entry: ansible-doctor -f
  language: python
  pass_filenames: False
  always_run: True
