FROM python:3.14-alpine@sha256:26730869004e2b9c4b9ad09cab8625e81d256d1ce97e72df5520e806b1709f92

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="ansible-doctor"
LABEL org.opencontainers.image.url="https://ansible-doctor.geekdocs.de/"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/ansible-doctor"
LABEL org.opencontainers.image.documentation="https://ansible-doctor.geekdocs.de/"

ENV PY_COLORS=1
ENV TZ=UTC

ADD dist/ansible_doctor-*.whl /

RUN apk --update add --virtual .build-deps build-base libffi-dev openssl-dev git && \
    apk --no-cache upgrade xz-libs sqlite-libs zlib && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir $(find / -name "ansible_doctor-*.whl")[ansible-core] && \
    rm -f ansible_doctor-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/ansible-doctor"]
