---
logging:
  level: debug

template:
  src: git>https://github.com/thegeeklab/ansible-doctor
  name: ansibledoctor/templates/readme

renderer:
  include_header: HEADER.md

annotations:
  var:
    subtypes: ["custom", "another_custom"]
  tag:
    subtypes: ["custom_field"]
