FROM arm32v7/python:3.9-alpine@sha256:7c62c7fb94b48a52b931f17b46c2451923fefa9ea759489b02b1a4b8441b5852

LABEL maintainer="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.authors="Robert Kaussow <mail@thegeeklab.de>"
LABEL org.opencontainers.image.title="ansible-doctor"
LABEL org.opencontainers.image.url="https://ansible-doctor.geekdocs.de/"
LABEL org.opencontainers.image.source="https://github.com/thegeeklab/ansible-doctor"
LABEL org.opencontainers.image.documentation="https://ansible-doctor.geekdocs.de/"

ENV PY_COLORS=1

ADD dist/ansible_doctor-*.whl /

RUN apk update && \
    pip install --upgrade --no-cache-dir pip && \
    pip install --no-cache-dir $(find / -name "ansible_doctor-*.whl") && \
    rm -f ansible_doctor-*.whl && \
    rm -rf /var/cache/apk/* && \
    rm -rf /root/.cache/

USER root
CMD []
ENTRYPOINT ["/usr/local/bin/ansible-doctor"]
