---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/auto/*

steps:
  - name: build
    image: docker.io/library/python:3.12
    commands:
      - pip install poetry poetry-dynamic-versioning -qq
      - poetry build

  - name: checksum
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - cd dist/ && sha256sum * > ../sha256sum.txt

  - name: changelog
    image: quay.io/thegeeklab/git-sv
    commands:
      - git sv current-version
      - git sv release-notes -t ${CI_COMMIT_TAG:-next} -o CHANGELOG.md
      - cat CHANGELOG.md

  - name: publish-github
    image: docker.io/plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/*
        - sha256sum.txt
      note: CHANGELOG.md
      overwrite: true
      title: ${CI_COMMIT_TAG}
    when:
      - event: [tag]

  - name: publish-pypi
    image: docker.io/library/python:3.12
    secrets:
      - source: pypi_password
        target: POETRY_HTTP_BASIC_PYPI_PASSWORD
      - source: pypi_username
        target: POETRY_HTTP_BASIC_PYPI_USERNAME
    commands:
      - pip install poetry poetry-dynamic-versioning -qq
      - poetry publish -n
    when:
      - event: [tag]

depends_on:
  - lint
  - test
