---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  build:
    image: docker.io/library/python:3.12
    commands:
      - git fetch --depth=2147483647
      - pip install poetry poetry-dynamic-versioning -qq
      - poetry build

  checksum:
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - cd dist/ && sha256sum * > ../sha256sum.txt

  changelog:
    image: quay.io/thegeeklab/git-sv
    commands:
      - git fetch --depth=2147483647
      - git sv current-version
      - git sv release-notes
      - git sv release-notes -o CHANGELOG.md

  publish-github:
    image: docker.io/plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - dist/*
        - sha256sum.txt
      note: CHANGELOG.md
      overwrite: true
      title: ${CI_COMMIT_TAG}
    when:
      - event: [tag]

  publish-pypi:
    image: docker.io/library/python:3.12
    secrets:
    - source: pypi_password
      target:  POETRY_HTTP_BASIC_PYPI_PASSWORD
    - source: pypi_username
      target:  POETRY_HTTP_BASIC_PYPI_USERNAME
    commands:
      - git fetch --depth=2147483647
      - pip install poetry poetry-dynamic-versioning -qq
      - poetry publish -n
    when:
      - event: [tag]

depends_on:
  - lint
  - test
