---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  assets:
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - make doc

  markdownlint:
    image: quay.io/thegeeklab/markdownlint-cli
    group: test
    commands:
      - markdownlint 'README.md' 'CONTRIBUTING.md'

  spellcheck:
    image: quay.io/thegeeklab/alpine-tools
    group: test
    commands:
      - spellchecker --files '_docs/**/*.md' 'README.md' 'CONTRIBUTING.md' -d .dictionary -p spell indefinite-article syntax-urls
    environment:
      FORCE_COLOR: "true"
      NPM_CONFIG_LOGLEVEL: "error"

  link-validation:
    image: docker.io/lycheeverse/lychee
    group: test
    commands:
      - lychee --no-progress --format detailed docs/content README.md

  testbuild:
    image: quay.io/thegeeklab/hugo:0.115.2
    commands:
      - hugo --panicOnWarning -s docs/ -b http://localhost:8000/

  build:
    image: quay.io/thegeeklab/hugo:0.115.2
    commands:
      - hugo --panicOnWarning -s docs/

  beautify:
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - html-beautify -r -f 'docs/public/**/*.html'
    environment:
      FORCE_COLOR: "true"
      NPM_CONFIG_LOGLEVEL: error

  publish:
    image: quay.io/thegeeklab/wp-s3-action
    settings:
      access_key:
        from_secret: s3_access_key
      bucket: geekdocs
      delete: true
      endpoint:
        from_secret: s3_endpoint
      path_style: true
      secret_key:
        from_secret: s3_secret_access_key
      source: docs/public/
      strip_prefix: docs/public/
      target: /${CI_REPO_NAME}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

  pushrm-dockerhub:
    image: docker.io/chko/docker-pushrm:1
    secrets:
      - source: docker_password
        target:  DOCKER_PASS
      - source: docker_username
        target:  DOCKER_USER
    environment:
      PUSHRM_FILE: README.md
      PUSHRM_SHORT: Annotation based documentation for your Ansible roles
      PUSHRM_TARGET: ${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

  pushrm-quay:
    image: docker.io/chko/docker-pushrm:1
    secrets:
      - source: quay_token
        target: APIKEY__QUAY_IO
    environment:
      PUSHRM_FILE: README.md
      PUSHRM_TARGET: quay.io/${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

depends_on:
  - build-package
  - build-container
