---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: assets
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - make doc

  - name: build
    image: quay.io/thegeeklab/hugo:0.156
    depends_on: [assets]
    commands:
      - hugo --panicOnWarning -s docs/

  - name: beautify
    image: quay.io/thegeeklab/alpine-tools
    depends_on: [build]
    commands:
      - html-beautify -r -f 'docs/public/**/*.html'

  - name: publish
    image: quay.io/thegeeklab/wp-s3-action
    depends_on: [beautify]
    settings:
      access_key:
        from_secret: s3_access_key
      bucket: geekdocs
      delete: true
      endpoint:
        from_secret: s3_endpoint
      path_style: true
      secret_key:
        from_secret: s3_secret_access_key
      source: docs/public/
      strip_prefix: docs/public/
      target: /${CI_REPO_NAME}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success, failure]

  - name: pushrm-dockerhub
    image: docker.io/chko/docker-pushrm:1
    depends_on: [beautify]
    environment:
      DOCKER_PASS:
        from_secret: docker_password
      DOCKER_USER:
        from_secret: docker_username
      PUSHRM_FILE: README.md
      PUSHRM_SHORT: Annotation based documentation for your Ansible roles
      PUSHRM_TARGET: ${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

  - name: pushrm-quay
    image: docker.io/chko/docker-pushrm:1
    depends_on: [beautify]
    environment:
      APIKEY__QUAY_IO:
        from_secret: quay_token
      PUSHRM_FILE: README.md
      PUSHRM_TARGET: quay.io/${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

depends_on:
  - build-package
  - build-container
