---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}
      - renovate/auto/*

steps:
  - name: assets
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - make doc

  - name: markdownlint
    image: quay.io/thegeeklab/markdownlint-cli
    group: test
    commands:
      - markdownlint 'README.md' 'CONTRIBUTING.md'

  - name: spellcheck
    image: quay.io/thegeeklab/alpine-tools
    group: test
    commands:
      - spellchecker --files 'docs/**/*.md' 'README.md' 'CONTRIBUTING.md' -d .dictionary -p spell indefinite-article syntax-urls
    environment:
      FORCE_COLOR: "true"

  - name: link-validation
    image: docker.io/lycheeverse/lychee
    group: test
    commands:
      - lychee --no-progress --format detailed docs/content README.md

  - name: build
    image: quay.io/thegeeklab/hugo:0.121.2
    commands:
      - hugo --panicOnWarning -s docs/

  - name: beautify
    image: quay.io/thegeeklab/alpine-tools
    commands:
      - html-beautify -r -f 'docs/public/**/*.html'
    environment:
      FORCE_COLOR: "true"

  - name: publish
    image: quay.io/thegeeklab/wp-s3-action
    settings:
      access_key:
        from_secret: s3_access_key
      bucket: geekdocs
      delete: true
      endpoint:
        from_secret: s3_endpoint
      path_style: true
      secret_key:
        from_secret: s3_secret_access_key
      source: docs/public/
      strip_prefix: docs/public/
      target: /${CI_REPO_NAME}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success, failure]

  - name: pushrm-dockerhub
    image: docker.io/chko/docker-pushrm:1
    secrets:
      - source: docker_password
        target: DOCKER_PASS
      - source: docker_username
        target: DOCKER_USER
    environment:
      PUSHRM_FILE: README.md
      PUSHRM_SHORT: Annotation based documentation for your Ansible roles
      PUSHRM_TARGET: ${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

  - name: pushrm-quay
    image: docker.io/chko/docker-pushrm:1
    secrets:
      - source: quay_token
        target: APIKEY__QUAY_IO
    environment:
      PUSHRM_FILE: README.md
      PUSHRM_TARGET: quay.io/${CI_REPO}
    when:
      - event: [push, manual]
        branch:
          - ${CI_REPO_DEFAULT_BRANCH}
        status: [success]

depends_on:
  - build-package
  - build-container
