---
when:
  - event: [pull_request, tag]
  - event: [push, manual]
    branch:
      - ${CI_REPO_DEFAULT_BRANCH}

steps:
  - name: check-format
    image: docker.io/library/python:3.12
    commands:
      - pip install poetry poetry-dynamic-versioning -qq
      - poetry install -E ansible-core
      - poetry run ruff format --check --diff ./${CI_REPO_NAME//-/}
    environment:
      PY_COLORS: "1"

  - name: check-coding
    image: docker.io/library/python:3.12
    commands:
      - pip install poetry poetry-dynamic-versioning -qq
      - poetry install -E ansible-core
      - poetry run ruff check ./${CI_REPO_NAME//-/}
    environment:
      PY_COLORS: "1"

  - name: check-jinja
    image: docker.io/library/python:3.12
    commands:
      - pip install poetry poetry-dynamic-versioning -qq
      - poetry install -E ansible-core
      - poetry run j2lint ansibledoctor/templates/ -i jinja-statements-indentation jinja-statements-delimiter
    environment:
      PY_COLORS: "1"
